name: Gene Identification CI/CD
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-notebook nbconvert jupyter
        if [ -f Requirements.txt ]; then
          pip install -r Requirements.txt
        else
          echo "Warning: Requirements.txt not found"
        fi

    - name: Create test data
      run: |
        python - <<EOF
        import pandas as pd
        import numpy as np
        import os
        
        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)
        
        # Create synthetic test data
        test_data = pd.DataFrame({
            'sequence': ['ATCG', 'GCTA', 'TGCA'],
            'label': ['gene1', 'gene2', 'gene3'],
            'score': np.random.random(3)
        })
        
        # Save test data in the data directory
        test_data.to_csv('data/data_cleaned.csv', index=False)
        print("Test data created successfully")
        EOF
    
    - name: Setup test environment
      run: |
        # Create an empty __init__.py to make the directory a Python package
        touch __init__.py
        
        # Create a basic test file if it doesn't exist
        if [ ! -f test_app.py ]; then
          echo """
import pytest
from app import *  # Import your app functions

def test_basic():
    assert True  # Add your actual tests here
          """ > test_app.py
        fi
    
    - name: Run Python tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}"
        # First run pytest on the test files
        pytest test_app.py -v
        
        # Then handle the notebook if it exists
        if [ -f GeneIdentification.ipynb ]; then
          jupyter nbconvert --to python GeneIdentification.ipynb
          pytest GeneIdentification.py -v
        else
          echo "Warning: GeneIdentification.ipynb not found"
        fi

  

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOL'
        FROM python:3.10-slim

        WORKDIR /app

        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            gcc \
            g++ \
            && rm -rf /var/lib/apt/lists/*

        # Copy requirements first to leverage Docker cache
        COPY Requirements.txt .
        RUN pip install --no-cache-dir -r Requirements.txt

        # Copy the project files
        COPY app.py .
        COPY GeneIdentification.ipynb .
        COPY data_cleaned.csv .
        COPY Data/ ./Data/

        # Set Python path
        ENV PYTHONPATH=/app

        # Run the application
        CMD ["python", "app.py"]
        EOL
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gene-identification:latest
          ${{ secrets.DOCKER_USERNAME }}/gene-identification:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gene-identification:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gene-identification:buildcache,mode=max
    
    - name: Run smoke test
      run: |
        docker run ${{ secrets.DOCKER_USERNAME }}/gene-identification:${{ github.sha }} python -c "import app; print('Smoke test passed')"
