name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run tests
      run: |
        pip install -r requirements.txt
        python -m pytest tests/

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gene-hmm:latest
          ${{ secrets.DOCKER_USERNAME }}/gene-hmm:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gene-hmm:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gene-hmm:buildcache,mode=max

    - name: Run smoke test
      run: |
        docker run ${{ secrets.DOCKER_USERNAME }}/gene-hmm:${{ github.sha }} python -c "import bio_hmm; print('Smoke test passed')"
